# Welcome to Jekyll!

# Website settings
title: Anuj Nagpal
description: Welcome to my homepage!
keywords: Anuj,Nagpal,IIT,Kanpur,Stanford,ICME,Computational,Mathematical,Engineering,anujnag,Goldman Sachs,Meta
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://anujnag.github.io  # url should be changed to 'http://www.jack003.com/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be changed to '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Anuj Nagpal  # Be used at blog posts' author.
  first_name: Anuj # Be used at index page about me section.
  last_name: Nagpal  # Be used at index page about me section.
  cv: Anuj_Resume.pdf  # A online CV can be printed as PDF, leave blank if you don't have now
  email: anujnagpal96@gmail.com  # Leave blank if you don't have now
  facebook_username: anuj.nagpal.731  # Leave blank if you don't have now
  github_username: anujnag  # Leave blank if you don't have now
  avatar: /static/assets/img/landing/DP.jpg  # upload your avatar at directory and edit it.
  skill_icon1:
    - name: fa-superpowers
    - name: fa-fort-awesome
  skill_icon2:
    - name: fa-fort-awesome
    - name: fa-superpowers
  desc: Hi there! I am a graduate student in Stanford University's majoring in Computational and Mathematical Engineering. I did my undergraduate in Computer Science and Engineering from Indian Institute of Technology Kanpur and joined Goldman Sachs after that in their Global Markets division (formerly known as Securities). My primary interests revolve around deep generative models, reinforcement learning, natural language processing and graph machine learning. Apart from my academic interests, I deeply love listening to music and a big time fan of rock genre (do you have a recommendation for a new song?). I love playing guitar in my free time and I've been lately picking up on tennis. Emails work best for contacting me!


# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#  name: jalpc
#  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
    id: UA-92624039-1

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
